import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  // No manual `icons` entry: Next's file-based metadata convention (#11)
  // auto-discovers `src/app/icon.svg` and injects the right <link> tag on
  // its own — an explicit `icons` field here would suppress that discovery
  // instead of merging with it (verified against the current Next.js docs,
  // not assumed — see the app-icons metadata file-conventions page).
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
